#!/bin/bash

#Easyemwm dependency grabber/installer
#author: cameronos
#date: 11/14/2025

#script installs all dependencies, tries to build emwm from source on Debian-type distros
#could be modified for any distro, just convert the apt installs to whatever package manager has these on your system


###Dependencies
set -e
echo "Updating package list.."
sudo apt update

echo "Installing build tools"
sudo apt install -y build-essential cmake automake autoconf libtool pkg-config

echo "Installing x11 development libraries"
sudo apt install -y libx11-dev libxt-dev libxext-dev libxrandr-dev libxinerama-dev libxpm-dev

echo "Installing Xorg and some apps, if haven't already"
sudo apt install -y xorg x11-apps xterm

echo "Installing Motif/OpenMotif development libraries"
sudo apt install -y libmotif-dev libxm4

echo "Installing helpful tools for grabbing repo"
sudo apt install -y git curl

###Cloning and Making
echo "Cloning repo.."
git clone https://github.com/alx210/emwm.git
clear

echo "Proceeding into dir, making and hopefully running"
cd emwm
sudo make

#Copying over emwmrc menu
sudo cp src/system.emwmrc ~/.emwmrc

#Pushing emwm to /usr/bin
sudo install -m 755 src/emwm /usr/bin/emwm
cd ..
pwd

echo "Cleaning post-directory make"
sudo rm -rf emwm/
sleep 1

###Xinitrc and Starting
echo "Creating .xinitrc for Xorg..."
cat > "$HOME/.xinitrc" << 'EOF'
#!/bin/sh
# xinitrc script for starting emwm with some apps
# edit me! I was generated by the installer

#Do not remove line below - handles xresources for DE
xrdb -merge ~/.xresources

xterm -bg black -fg white -e "less $HOME/easyemwm/postInstall.md" &
xclock &
exec /usr/bin/emwm
EOF

chmod +x "$HOME/.xinitrc"
echo "Xinitrc file created"

clear
echo "Install finished. Attempting to start DE. Exit by killing Xorg for now..."
sleep 2
startx
